# Base path -- EDIT THIS ONCE, then run this chunk first
```{r}

# ---------------------------------------------------------------------------
# "base" = the folder that contains BOTH the model folders
# (7_Modele_AGB_sans_montane, ...) AND this graph folder (8_Graph).
# Put here the path to that folder on your machine: every path in the script
# is then built automatically from it (base + subfolder + file).
base <- "path/to/your/folder"
```

#Importation
##Direct DAG + direct coefficient table
```{r }
rm(list = setdiff(ls(), "base")) 

setwd(file.path(base, "8_Graph"))

#Libraries
library(data.table) #is used to import and manipulate tables
library(ggplot2)
library(qgraph)
library(igraph)

library(ggraph)
library(tidyverse)

# Plot dataset + pioneer % : loaded once here, used by all sections below
brut <- fread( "Pantropical_dataset_2023plots_V2_N_55_1_SOIL.csv")
brut <- brut[!elevation.y >= 1000]   # remove montane plots (elevation >= 1000 m)
pion <- fread("pourc_pionnier_Af.csv")
#Table: for all continents and all response variables, total effect of environment on each response variable (attributs and AGBs)
mean_coef_all_all<-fread("mean_coef_all_all.csv")
rmse_mean_all_all<-fread("rmse_mean_all_all.csv")
rmse_mean_all_all<-rmse_mean_all_all[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais<-dcast(mean_coef_all_all,sub_rep + area + var~est,value.var="mean_coef2")

#Direct effect of environment on BA
mean_coef_ba<-fread("mean_coef_ba_dbh_sd.csv")
rmse_mean_ba<-fread("rmse_mean_ba_dbh_sd.csv")
rmse_mean_ba<-rmse_mean_ba[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais2<-dcast(mean_coef_ba,sub_rep + area + var~est,value.var="mean_coef2")

#Direct effect of environment on DBHqm
mean_coef_dbh<-fread("mean_coef_dbh_sd.csv")
rmse_mean_dbh<-fread("rmse_mean_dbh_sd.csv")
rmse_mean_dbh<-rmse_mean_dbh[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais3<-dcast(mean_coef_dbh,sub_rep + area + var~est,value.var="mean_coef2")


#Direct effect of environment on DBHqm
mean_coef_wdba<-fread("mean_coef_wdba_ba.csv")
rmse_mean_wdba<-fread("rmse_mean_wdba_ba.csv")
rmse_mean_wdba<-rmse_mean_wdba[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais2bis<-dcast(mean_coef_wdba,sub_rep + area + var~est,value.var="mean_coef2")

#Direct effect of attributes on AGB
mean_coef_agb<-fread("mean_coef_agb.csv")
rmse_mean_agb<-fread("rmse_mean_agb.csv")
rmse_mean_agb<-rmse_mean_agb[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais4<-dcast(mean_coef_agb,sub_rep + area + var~est,value.var="mean_coef2")


#Direct effect of attributes on AGB
mean_coef_agb_all<-fread("mean_coef_agb_all.csv")
rmse_mean_agb_all<-fread("rmse_mean_agb_all.csv")
rmse_mean_agb_all<-rmse_mean_agb_all[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais4bis<-dcast(mean_coef_agb_all,sub_rep + area + var~est,value.var="mean_coef2")

#Total effect of attributes on AGB
mean_coef_agb_sd<-fread("mean_coef_agb_sd.csv")
rmse_mean_agb_sd<-fread("rmse_mean_agb_sd.csv")
rmse_mean_agb_sd<-rmse_mean_agb_sd[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais5<-dcast(mean_coef_agb_sd,sub_rep + area + var~est,value.var="mean_coef2")

mean_coef_agb_dbh_sd<-fread("mean_coef_agb_dbh_sd.csv")
rmse_mean_agb_dbh_sd<-fread("rmse_mean_agb_dbh_sd.csv")
rmse_mean_agb_dbh_sd<-rmse_mean_agb_dbh_sd[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais6<-dcast(mean_coef_agb_dbh_sd,sub_rep + area + var~est,value.var="mean_coef2")

mean_coef_agb_wdba<-fread("mean_coef_agb_wdba.csv")
rmse_mean_agb_wdba<-fread("rmse_mean_agb_wdba.csv")
rmse_mean_agb_wdba<-rmse_mean_agb_wdba[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais7<-dcast(mean_coef_agb_wdba,sub_rep + area + var~est,value.var="mean_coef2")


##Africa with Proportion####################################################################################################################################################

#Table: for all continents and all response variables, total effect of environment on each response variable (attributs and AGBs)
mean_coef_all_all_af<-fread("mean_coef_all_all_af.csv")
rmse_mean_all_all_af<-fread("rmse_mean_all_all_af.csv")
rmse_mean_all_all_af<-rmse_mean_all_all_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais_af<-dcast(mean_coef_all_all_af,sub_rep + area + var~est,value.var="mean_coef2")

#Direct effect of environment on BA
mean_coef_ba_af<-fread("mean_coef_ba_dbh_sd_af.csv")
rmse_mean_ba_af<-fread("rmse_mean_ba_dbh_sd_af.csv")
rmse_mean_ba_af<-rmse_mean_ba_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais2_af<-dcast(mean_coef_ba_af,sub_rep + area + var~est,value.var="mean_coef2")

#Direct effect of environment on DBHqm
mean_coef_dbh_af<-fread("mean_coef_dbh_sd_af.csv")
rmse_mean_dbh_af<-fread("rmse_mean_dbh_sd_af.csv")
rmse_mean_dbh_af<-rmse_mean_dbh_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais3_af<-dcast(mean_coef_dbh_af,sub_rep + area + var~est,value.var="mean_coef2")


#Direct effect of environment on DBHqm
mean_coef_wdba_af<-fread("mean_coef_wdba_ba_af.csv")
rmse_mean_wdba_af<-fread("rmse_mean_wdba_ba_af.csv")
rmse_mean_wdba_af<-rmse_mean_wdba_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais2bis_af<-dcast(mean_coef_wdba_af,sub_rep + area + var~est,value.var="mean_coef2")


#Direct effect of attributes on AGB
mean_coef_agb_af<-fread("mean_coef_agb_af.csv")
rmse_mean_agb_af<-fread("rmse_mean_agb_af.csv")
rmse_mean_agb_af<-rmse_mean_agb_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais4_af<-dcast(mean_coef_agb_af,sub_rep + area + var~est,value.var="mean_coef2")


#Direct effect of attributes on AGB
mean_coef_agb_all_af<-fread("mean_coef_agb_all_af.csv")
rmse_mean_agb_all_af<-fread("rmse_mean_agb_all_af.csv")
rmse_mean_agb_all_af<-rmse_mean_agb_all_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais4bis_af<-dcast(mean_coef_agb_all_af,sub_rep + area + var~est,value.var="mean_coef2")

#Total effect of attributes on AGB
mean_coef_agb_sd_af<-fread("mean_coef_agb_sd_af.csv")
rmse_mean_agb_sd_af<-fread("rmse_mean_agb_sd_af.csv")
rmse_mean_agb_sd_af<-rmse_mean_agb_sd_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais5_af<-dcast(mean_coef_agb_sd_af,sub_rep + area + var~est,value.var="mean_coef2")

mean_coef_agb_dbh_sd_af<-fread("mean_coef_agb_dbh_sd_af.csv")
rmse_mean_agb_dbh_sd_af<-fread("rmse_mean_agb_dbh_sd_af.csv")
rmse_mean_agb_dbh_sd_af<-rmse_mean_agb_dbh_sd_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais6_af<-dcast(mean_coef_agb_dbh_sd_af,sub_rep + area + var~est,value.var="mean_coef2")

mean_coef_agb_wdba_af<-fread("mean_coef_agb_wdba_af.csv")
rmse_mean_agb_wdba_af<-fread("rmse_mean_agb_wdba_af.csv")
rmse_mean_agb_wdba_af<-rmse_mean_agb_wdba_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais7_af<-dcast(mean_coef_agb_wdba_af,sub_rep + area + var~est,value.var="mean_coef2")

mean_coef_agb_prop_af<-fread("mean_coef_agb_prop_af.csv")
rmse_mean_agb_prop_af<-fread("rmse_mean_agb_prop_af.csv")
rmse_mean_agb_prop_af<-rmse_mean_agb_prop_af[,.(rmse=mean(rmse),rsquared=mean(r_squared)),by=c("sub_rep","area")]
#still need to pivot so 'est' is in columns, using mean_coef2
essais8_af<-dcast(mean_coef_agb_prop_af,sub_rep + area + var~est,value.var="mean_coef2")

#############################################################################################################################################################################

essais[,unique(area)]
essais[area=="north America",area:="north_america"]
essais[area=="Oceania",area:="oceania"]

essais2[,unique(area)]
essais2[area=="North America",area:="north_america"]
essais2[area=="Oceania",area:="oceania"]

essais2bis[,unique(area)]
essais2bis[area=="North America",area:="north_america"]
essais2bis[area=="Oceania",area:="oceania"]

essais3[,unique(area)]
essais3[area=="North America",area:="north_america"]
essais3[area=="Oceania",area:="oceania"]


essais4[,unique(area)]
essais4[area=="North America",area:="north_america"]
essais4[area=="Oceania",area:="oceania"]

essais4bis[,unique(area)]
essais4bis[area=="North America",area:="north_america"]
essais4bis[area=="Oceania",area:="oceania"]


essais5[,unique(area)]
essais5[area=="North America",area:="north_america"]
essais5[area=="Oceania",area:="oceania"]

essais6[,unique(area)]
essais6[area=="North America",area:="north_america"]
essais6[area=="Oceania",area:="oceania"]

essais7[,unique(area)]
essais7[area=="North America",area:="north_america"]
essais7[area=="Oceania",area:="oceania"]

rmse_mean_agb_all[area=="North America",area:="north_america"]
rmse_mean_agb_all_af[area=="North America",area:="north_america"]
rmse_mean_agb[area=="North America",area:="north_america"]
rmse_mean_agb_af[area=="North America",area:="north_america"]
rmse_mean_agb_dbh_sd[area=="North America",area:="north_america"]
rmse_mean_agb_dbh_sd_af[area=="North America",area:="north_america"]
rmse_mean_agb_sd[area=="North America",area:="north_america"]
rmse_mean_agb_sd_af[area=="North America",area:="north_america"]
rmse_mean_all_all[area=="north America",area:="north_america"]
rmse_mean_all_all_af[area=="North America",area:="north_america"]
rmse_mean_ba[area=="North America",area:="north_america"]
rmse_mean_ba_af[area=="North America",area:="north_america"]
rmse_mean_dbh[area=="North America",area:="north_america"]
rmse_mean_dbh_af[area=="North America",area:="north_america"]
rmse_mean_wdba[area=="North America",area:="north_america"]
rmse_mean_wdba_af[area=="North America",area:="north_america"]
rmse_mean_agb_wdba[area=="North America",area:="north_america"]
rmse_mean_agb_wdba_af[area=="North America",area:="north_america"]

rmse_mean_agb_all[area=="Oceania",area:="oceania"]
rmse_mean_agb_all_af[area=="Oceania",area:="oceania"]
rmse_mean_agb[area=="Oceania",area:="oceania"]
rmse_mean_agb_af[area=="Oceania",area:="oceania"]
rmse_mean_agb_dbh_sd[area=="Oceania",area:="oceania"]
rmse_mean_agb_dbh_sd_af[area=="Oceania",area:="oceania"]
rmse_mean_agb_sd[area=="Oceania",area:="oceania"]
rmse_mean_agb_sd_af[area=="Oceania",area:="oceania"]
rmse_mean_all_all[area=="Oceania",area:="oceania"]
rmse_mean_all_all_af[area=="Oceania",area:="oceania"]
rmse_mean_ba[area=="Oceania",area:="oceania"]
rmse_mean_ba_af[area=="Oceania",area:="oceania"]
rmse_mean_dbh[area=="Oceania",area:="oceania"]
rmse_mean_dbh_af[area=="Oceania",area:="oceania"]
rmse_mean_wdba[area=="Oceania",area:="oceania"]
rmse_mean_wdba_af[area=="Oceania",area:="oceania"]
rmse_mean_agb_wdba[area=="Oceania",area:="oceania"]
rmse_mean_agb_wdba_af[area=="Oceania",area:="oceania"]

rmse_mean_agb_all[,unique(area)]
rmse_mean_agb_all_af[,unique(area)]
rmse_mean_agb[,unique(area)]
rmse_mean_agb_af[,unique(area)]
rmse_mean_agb_dbh_sd[,unique(area)]
rmse_mean_agb_dbh_sd_af[,unique(area)]
rmse_mean_agb_sd[,unique(area)]
rmse_mean_agb_sd_af[,unique(area)]
rmse_mean_all_all[,unique(area)]
rmse_mean_all_all_af[,unique(area)]
rmse_mean_ba[,unique(area)]
rmse_mean_ba_af[,unique(area)]
rmse_mean_dbh[,unique(area)]
rmse_mean_dbh_af[,unique(area)]
rmse_mean_wdba[,unique(area)]
rmse_mean_wdba_af[,unique(area)]
rmse_mean_agb_wdba[,unique(area)]
rmse_mean_agb_wdba_af[,unique(area)]

essais_af[,unique(area)]
essais2_af[,unique(area)]
essais3_af[,unique(area)]
essais2_af[,unique(area)]
essais5_af[,unique(area)]
essais6_af[,unique(area)]
essais7_af[,unique(area)]
essais2bis_af[,unique(area)]
essais4bis_af[,unique(area)]

essais[,unique(area)]
essais2[,unique(area)]
essais3[,unique(area)]
essais4[,unique(area)]
essais5[,unique(area)]
essais6[,unique(area)]
essais7[,unique(area)]
essais2bis[,unique(area)]
essais4bis[,unique(area)]
```
###Oceania

```{r }
mean_ba<-brut[Continent=="Oceania"][!is.na(BA),mean(BA)]
sd_ba<-brut[Continent=="Oceania"][!is.na(BA),sd(BA)]

mean_dbh<-brut[Continent=="Oceania"][!is.na(DBHqm),mean(DBHqm)]
sd_dbh<-brut[Continent=="Oceania"][!is.na(DBHqm),sd(DBHqm)]

mean_sd<-brut[Continent=="Oceania"][!is.na(SD),mean(SD)]
sd_sd<-brut[Continent=="Oceania"][!is.na(SD),sd(SD)]

mean_wd<-brut[Continent=="Oceania"][!is.na(WDba),mean(WDba)]
sd_wd<-brut[Continent=="Oceania"][!is.na(WDba),sd(WDba)]

mean_agb<-brut[Continent=="Oceania"][!is.na(AGB_Feld_Pan),mean(AGB_Feld_Pan)]
sd_agb<-brut[Continent=="Oceania"][!is.na(AGB_Feld_Pan),sd(AGB_Feld_Pan)]

mean_agbcont<-brut[Continent=="Oceania"][!is.na(AGB_Feld_Cont),mean(AGB_Feld_Cont)]
sd_agbcont<-brut[Continent=="Oceania"][!is.na(AGB_Feld_Cont),sd(AGB_Feld_Cont)]

mean_agbreg<-brut[Continent=="Oceania"][!is.na(AGB_Feld_Reg),mean(AGB_Feld_Reg)]
sd_agbreg<-brut[Continent=="Oceania"][!is.na(AGB_Feld_Reg),sd(AGB_Feld_Reg)]


a<-essais2[area=="oceania",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
b<-essais3[area=="oceania",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
c<-essais2bis[area=="oceania",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
d<-essais[area=="oceania",.(from=var,to=sub_rep,coef=estimate)][to=="SD"]# I have all the direct effects toward attributes and among attributes
g<-essais[area=="oceania",.(from=var,to=sub_rep,coef=estimate)][!to=="DBH_qm"&!to=="SD"&!to=="WDba"&!to=="BA"&!to=="AGB_Feld_Cont"&!to=="AGB_Feld_Reg"]# env sur AGB



edges<-rbind(a,b,c,d,g)
edges[to=="DBH_qm",to:="DBHqm"]
edges[!from=="DBH_qm"&!from=="SD"&!from=="WDba"&!from=="BA"]
#standardize the coefficients (in standard deviation and in %)
edges[to=="BA",coef_sd:=coef/sd_ba]
edges[to=="BA",coef_pourc:=(coef/mean_ba)*100]

edges[to=="SD",coef_sd:=coef/sd_sd]
edges[to=="SD",coef_pourc:=(coef/mean_sd)*100]

edges[to=="DBHqm",coef_sd:=coef/sd_dbh]
edges[to=="DBHqm",coef_pourc:=(coef/mean_dbh)*100]


edges[to=="WDba",coef_sd:=coef/sd_wd]
edges[to=="WDba",coef_pourc:=(coef/mean_wd)*100]


edges[to=="AGB_Feld_Pan",coef_sd:=coef/sd_agb]
edges[to=="AGB_Feld_Pan",coef_pourc:=(coef/mean_agb)*100]


edges[to=="AGB_Feld_Reg",coef_sd:=coef/sd_agbreg]
edges[to=="AGB_Feld_Reg",coef_pourc:=(coef/mean_agbreg)*100]


edges[to=="AGB_Feld_Cont",coef_sd:=coef/sd_agbcont]
edges[to=="AGB_Feld_Cont",coef_pourc:=(coef/mean_agbcont)*100]

edges_brut<-edges
edges_brut2<-edges
data2<-edges_brut2[,area:="Oceania"]

###non-standardized coefficients

sd_bio1<-brut[Continent=="Oceania"][,.(Bio1_WC,Bio1_CHELSA,Bio1_CRU,Bio1_ERA5,Bio1_TC,Bio1_MODIS)]
sd_bio1[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio1<-sd_bio1[,sd(row_mean)]
data2[from=="bio1"&area=="Oceania",coef_brut:=(coef/sd_bio1)]

sd_bio12<-brut[Continent=="Oceania"][,.(Bio12_WC,Bio12_CHELSA,Bio12_CRU,Bio12_ERA5,Bio12_TC,Bio12_IMERG,Bio12_CHIRPS)]
sd_bio12[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio12<-sd_bio12[,sd(row_mean)]
data2[from=="bio12"&area=="Oceania",coef_brut:=(coef/sd_bio12)]

sd_bio15<-brut[Continent=="Oceania"][,.(Bio15_WC,Bio15_CHELSA,Bio15_CRU,Bio15_ERA5,Bio15_TC,Bio15_IMERG,Bio15_CHIRPS)]
sd_bio15[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio15<-sd_bio15[,sd(row_mean)]
data2[from=="bio15"&area=="Oceania",coef_brut:=(coef/sd_bio15)]

sd<-brut[Continent=="Oceania",sd(slope)]
data2[from=="slope"&area=="Oceania",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Oceania",sd(sand)]
data2[from=="sand"&area=="Oceania",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Oceania",sd(org)]
data2[from=="org"&area=="Oceania",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Oceania",sd(ph)]
data2[from=="ph"&area=="Oceania",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Oceania",sd(DBHqm)]
data2[from=="DBHqm"&area=="Oceania",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Oceania",sd(SD)]
data2[from=="SD"&area=="Oceania",coef_brut:=(coef/sd)]


sd<-brut[Continent=="Oceania",sd(BA)]
data2[from=="BA"&area=="Oceania",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Oceania",sd(WDba)]
data2[from=="WDba"&area=="Oceania",coef_brut:=(coef/sd)]

```


###North America
```{r }
mean_ba<-brut[Continent=="North America"][!is.na(BA),mean(BA)]
sd_ba<-brut[Continent=="North America"][!is.na(BA),sd(BA)]

mean_dbh<-brut[Continent=="North America"][!is.na(DBHqm),mean(DBHqm)]
sd_dbh<-brut[Continent=="North America"][!is.na(DBHqm),sd(DBHqm)]

mean_sd<-brut[Continent=="North America"][!is.na(SD),mean(SD)]
sd_sd<-brut[Continent=="North America"][!is.na(SD),sd(SD)]

mean_wd<-brut[Continent=="North America"][!is.na(WDba),mean(WDba)]
sd_wd<-brut[Continent=="North America"][!is.na(WDba),sd(WDba)]

mean_agb<-brut[Continent=="North America"][!is.na(AGB_Feld_Pan),mean(AGB_Feld_Pan)]
sd_agb<-brut[Continent=="North America"][!is.na(AGB_Feld_Pan),sd(AGB_Feld_Pan)]

mean_agbcont<-brut[Continent=="North America"][!is.na(AGB_Feld_Cont),mean(AGB_Feld_Cont)]
sd_agbcont<-brut[Continent=="North America"][!is.na(AGB_Feld_Cont),sd(AGB_Feld_Cont)]

mean_agbreg<-brut[Continent=="North America"][!is.na(AGB_Feld_Reg),mean(AGB_Feld_Reg)]
sd_agbreg<-brut[Continent=="North America"][!is.na(AGB_Feld_Reg),sd(AGB_Feld_Reg)]


a<-essais2[area=="north_america",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
b<-essais3[area=="north_america",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
c<-essais2bis[area=="north_america",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
d<-essais[area=="north_america",.(from=var,to=sub_rep,coef=estimate)][to=="SD"]#j'ai toutes els directes vers attributs and entre ttributs
g<-essais[area=="north_america",.(from=var,to=sub_rep,coef=estimate)][!to=="DBH_qm"&!to=="SD"&!to=="WDba"&!to=="BA"&!to=="AGB_Feld_Cont"&!to=="AGB_Feld_Reg"]# env sur AGB


edges<-rbind(a,b,c,d,g)
edges[to=="DBH_qm",to:="DBHqm"]
edges[!from=="DBH_qm"&!from=="SD"&!from=="WDba"&!from=="BA"]
#standardize the coefficients (in standard deviation and in %)
edges[to=="BA",coef_sd:=coef/sd_ba]
edges[to=="BA",coef_pourc:=(coef/mean_ba)*100]

edges[to=="SD",coef_sd:=coef/sd_sd]
edges[to=="SD",coef_pourc:=(coef/mean_sd)*100]

edges[to=="DBHqm",coef_sd:=coef/sd_dbh]
edges[to=="DBHqm",coef_pourc:=(coef/mean_dbh)*100]


edges[to=="WDba",coef_sd:=coef/sd_wd]
edges[to=="WDba",coef_pourc:=(coef/mean_wd)*100]


edges[to=="AGB_Feld_Pan",coef_sd:=coef/sd_agb]
edges[to=="AGB_Feld_Pan",coef_pourc:=(coef/mean_agb)*100]


edges[to=="AGB_Feld_Reg",coef_sd:=coef/sd_agbreg]
edges[to=="AGB_Feld_Reg",coef_pourc:=(coef/mean_agbreg)*100]


edges[to=="AGB_Feld_Cont",coef_sd:=coef/sd_agbcont]
edges[to=="AGB_Feld_Cont",coef_pourc:=(coef/mean_agbcont)*100]

edges_brut<-edges
edges_brut2<-edges
data<-edges_brut2[,area:="North America"]
data[,coef_brut:=NA]
data2<-rbind(data2,data)

###non-standardized coefficients

sd_bio1<-brut[Continent=="North America"][,.(Bio1_WC,Bio1_CHELSA,Bio1_CRU,Bio1_ERA5,Bio1_TC,Bio1_MODIS)]
sd_bio1[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio1<-sd_bio1[,sd(row_mean)]
data2[from=="bio1"&area=="North America",coef_brut:=(coef/sd_bio1)]

sd_bio12<-brut[Continent=="North America"][,.(Bio12_WC,Bio12_CHELSA,Bio12_CRU,Bio12_ERA5,Bio12_TC,Bio12_IMERG,Bio12_CHIRPS)]
sd_bio12[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio12<-sd_bio12[,sd(row_mean)]
data2[from=="bio12"&area=="North America",coef_brut:=(coef/sd_bio12)]

sd_bio15<-brut[Continent=="North America"][,.(Bio15_WC,Bio15_CHELSA,Bio15_CRU,Bio15_ERA5,Bio15_TC,Bio15_IMERG,Bio15_CHIRPS)]
sd_bio15[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio15<-sd_bio15[,sd(row_mean)]
data2[from=="bio15"&area=="North America",coef_brut:=(coef/sd_bio15)]

sd<-brut[Continent=="North America",sd(slope)]
data2[from=="slope"&area=="North America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="North America",sd(sand)]
data2[from=="sand"&area=="North America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="North America",sd(org)]
data2[from=="org"&area=="North America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="North America",sd(ph)]
data2[from=="ph"&area=="North America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="North America",sd(DBHqm)]
data2[from=="DBHqm"&area=="North America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="North America",sd(SD)]
data2[from=="SD"&area=="North America",coef_brut:=(coef/sd)]


sd<-brut[Continent=="North America",sd(BA)]
data2[from=="BA"&area=="North America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="North America",sd(WDba)]
data2[from=="WDba"&area=="North America",coef_brut:=(coef/sd)]
```



###South America
```{r }
mean_ba<-brut[Continent=="South America"][!is.na(BA),mean(BA)]
sd_ba<-brut[Continent=="South America"][!is.na(BA),sd(BA)]

mean_dbh<-brut[Continent=="South America"][!is.na(DBHqm),mean(DBHqm)]
sd_dbh<-brut[Continent=="South America"][!is.na(DBHqm),sd(DBHqm)]

mean_sd<-brut[Continent=="South America"][!is.na(SD),mean(SD)]
sd_sd<-brut[Continent=="South America"][!is.na(SD),sd(SD)]

mean_wd<-brut[Continent=="South America"][!is.na(WDba),mean(WDba)]
sd_wd<-brut[Continent=="South America"][!is.na(WDba),sd(WDba)]

mean_agb<-brut[Continent=="South America"][!is.na(AGB_Feld_Pan),mean(AGB_Feld_Pan)]
sd_agb<-brut[Continent=="South America"][!is.na(AGB_Feld_Pan),sd(AGB_Feld_Pan)]

mean_agbcont<-brut[Continent=="South America"][!is.na(AGB_Feld_Cont),mean(AGB_Feld_Cont)]
sd_agbcont<-brut[Continent=="South America"][!is.na(AGB_Feld_Cont),sd(AGB_Feld_Cont)]

mean_agbreg<-brut[Continent=="South America"][!is.na(AGB_Feld_Reg),mean(AGB_Feld_Reg)]
sd_agbreg<-brut[Continent=="South America"][!is.na(AGB_Feld_Reg),sd(AGB_Feld_Reg)]



a<-essais2[area=="south_america",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
b<-essais3[area=="south_america",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
c<-essais2bis[area=="south_america",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
d<-essais[area=="south_america",.(from=var,to=sub_rep,coef=estimate)][to=="SD"]#j'ai toutes els directes vers attributs and entre ttributs
g<-essais[area=="south_america",.(from=var,to=sub_rep,coef=estimate)][!to=="DBH_qm"&!to=="SD"&!to=="WDba"&!to=="BA"&!to=="AGB_Feld_Cont"&!to=="AGB_Feld_Reg"]# env sur AGB

edges<-rbind(a,b,c,d,g)
edges[to=="DBH_qm",to:="DBHqm"]
edges[!from=="DBH_qm"&!from=="SD"&!from=="WDba"&!from=="BA"]
#standardize the coefficients (in standard deviation and in %)
edges[to=="BA",coef_sd:=coef/sd_ba]
edges[to=="BA",coef_pourc:=(coef/mean_ba)*100]

edges[to=="SD",coef_sd:=coef/sd_sd]
edges[to=="SD",coef_pourc:=(coef/mean_sd)*100]

edges[to=="DBHqm",coef_sd:=coef/sd_dbh]
edges[to=="DBHqm",coef_pourc:=(coef/mean_dbh)*100]


edges[to=="WDba",coef_sd:=coef/sd_wd]
edges[to=="WDba",coef_pourc:=(coef/mean_wd)*100]


edges[to=="AGB_Feld_Pan",coef_sd:=coef/sd_agb]
edges[to=="AGB_Feld_Pan",coef_pourc:=(coef/mean_agb)*100]


edges[to=="AGB_Feld_Reg",coef_sd:=coef/sd_agbreg]
edges[to=="AGB_Feld_Reg",coef_pourc:=(coef/mean_agbreg)*100]


edges[to=="AGB_Feld_Cont",coef_sd:=coef/sd_agbcont]
edges[to=="AGB_Feld_Cont",coef_pourc:=(coef/mean_agbcont)*100]

edges_brut<-edges
edges_brut2<-edges
data<-edges_brut2[,area:="South America"]
data[,coef_brut:=NA]
data2<-rbind(data2,data)

###non-standardized coefficients

sd_bio1<-brut[Continent=="South America"][,.(Bio1_WC,Bio1_CHELSA,Bio1_CRU,Bio1_ERA5,Bio1_TC,Bio1_MODIS)]
sd_bio1[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio1<-sd_bio1[,sd(row_mean)]
data2[from=="bio1"&area=="South America",coef_brut:=(coef/sd_bio1)]

sd_bio12<-brut[Continent=="South America"][,.(Bio12_WC,Bio12_CHELSA,Bio12_CRU,Bio12_ERA5,Bio12_TC,Bio12_IMERG,Bio12_CHIRPS)]
sd_bio12[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio12<-sd_bio12[,sd(row_mean)]
data2[from=="bio12"&area=="South America",coef_brut:=(coef/sd_bio12)]

sd_bio15<-brut[Continent=="South America"][,.(Bio15_WC,Bio15_CHELSA,Bio15_CRU,Bio15_ERA5,Bio15_TC,Bio15_IMERG,Bio15_CHIRPS)]
sd_bio15[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio15<-sd_bio15[,sd(row_mean)]
data2[from=="bio15"&area=="South America",coef_brut:=(coef/sd_bio15)]

sd<-brut[Continent=="South America",sd(slope)]
data2[from=="slope"&area=="South America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="South America",sd(sand)]
data2[from=="sand"&area=="South America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="South America",sd(org)]
data2[from=="org"&area=="South America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="South America",sd(ph)]
data2[from=="ph"&area=="South America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="South America",sd(DBHqm)]
data2[from=="DBHqm"&area=="South America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="South America",sd(SD)]
data2[from=="SD"&area=="South America",coef_brut:=(coef/sd)]


sd<-brut[Continent=="South America",sd(BA)]
data2[from=="BA"&area=="South America",coef_brut:=(coef/sd)]

sd<-brut[Continent=="South America",sd(WDba)]
data2[from=="WDba"&area=="South America",coef_brut:=(coef/sd)]
```


###Asia
```{r }
mean_ba<-brut[Continent=="Eurasia"][!is.na(BA),mean(BA)]
sd_ba<-brut[Continent=="Eurasia"][!is.na(BA),sd(BA)]

mean_dbh<-brut[Continent=="Eurasia"][!is.na(DBHqm),mean(DBHqm)]
sd_dbh<-brut[Continent=="Eurasia"][!is.na(DBHqm),sd(DBHqm)]

mean_sd<-brut[Continent=="Eurasia"][!is.na(SD),mean(SD)]
sd_sd<-brut[Continent=="Eurasia"][!is.na(SD),sd(SD)]

mean_wd<-brut[Continent=="Eurasia"][!is.na(WDba),mean(WDba)]
sd_wd<-brut[Continent=="Eurasia"][!is.na(WDba),sd(WDba)]

mean_agb<-brut[Continent=="Eurasia"][!is.na(AGB_Feld_Pan),mean(AGB_Feld_Pan)]
sd_agb<-brut[Continent=="Eurasia"][!is.na(AGB_Feld_Pan),sd(AGB_Feld_Pan)]

mean_agbcont<-brut[Continent=="Eurasia"][!is.na(AGB_Feld_Cont),mean(AGB_Feld_Cont)]
sd_agbcont<-brut[Continent=="Eurasia"][!is.na(AGB_Feld_Cont),sd(AGB_Feld_Cont)]

mean_agbreg<-brut[Continent=="Eurasia"][!is.na(AGB_Feld_Reg),mean(AGB_Feld_Reg)]
sd_agbreg<-brut[Continent=="Eurasia"][!is.na(AGB_Feld_Reg),sd(AGB_Feld_Reg)]


a<-essais2[area=="asia",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
b<-essais3[area=="asia",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
c<-essais2bis[area=="asia",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
d<-essais[area=="asia",.(from=var,to=sub_rep,coef=estimate)][to=="SD"]#j'ai toutes els directes vers attributs and entre ttributs
g<-essais[area=="asia",.(from=var,to=sub_rep,coef=estimate)][!to=="DBH_qm"&!to=="SD"&!to=="WDba"&!to=="BA"&!to=="AGB_Feld_Cont"&!to=="AGB_Feld_Reg"]# env sur AGB

edges<-rbind(a,b,c,d,g)
edges[to=="DBH_qm",to:="DBHqm"]
edges[!from=="DBH_qm"&!from=="SD"&!from=="WDba"&!from=="BA"]
#standardize the coefficients (in standard deviation and in %)
edges[to=="BA",coef_sd:=coef/sd_ba]
edges[to=="BA",coef_pourc:=(coef/mean_ba)*100]

edges[to=="SD",coef_sd:=coef/sd_sd]
edges[to=="SD",coef_pourc:=(coef/mean_sd)*100]

edges[to=="DBHqm",coef_sd:=coef/sd_dbh]
edges[to=="DBHqm",coef_pourc:=(coef/mean_dbh)*100]


edges[to=="WDba",coef_sd:=coef/sd_wd]
edges[to=="WDba",coef_pourc:=(coef/mean_wd)*100]


edges[to=="AGB_Feld_Pan",coef_sd:=coef/sd_agb]
edges[to=="AGB_Feld_Pan",coef_pourc:=(coef/mean_agb)*100]


edges[to=="AGB_Feld_Reg",coef_sd:=coef/sd_agbreg]
edges[to=="AGB_Feld_Reg",coef_pourc:=(coef/mean_agbreg)*100]


edges[to=="AGB_Feld_Cont",coef_sd:=coef/sd_agbcont]
edges[to=="AGB_Feld_Cont",coef_pourc:=(coef/mean_agbcont)*100]

edges_brut<-edges
edges_brut2<-edges
data<-edges_brut2[,area:="Asia"]
data[,coef_brut:=NA]
data2<-rbind(data2,data)

###non-standardized coefficients

sd_bio1<-brut[Continent=="Eurasia"][,.(Bio1_WC,Bio1_CHELSA,Bio1_CRU,Bio1_ERA5,Bio1_TC,Bio1_MODIS)]
sd_bio1[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio1<-sd_bio1[,sd(row_mean)]
data2[from=="bio1"&area=="Asia",coef_brut:=(coef/sd_bio1)]

sd_bio12<-brut[Continent=="Eurasia"][,.(Bio12_WC,Bio12_CHELSA,Bio12_CRU,Bio12_ERA5,Bio12_TC,Bio12_IMERG,Bio12_CHIRPS)]
sd_bio12[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio12<-sd_bio12[,sd(row_mean)]
data2[from=="bio12"&area=="Asia",coef_brut:=(coef/sd_bio12)]

sd_bio15<-brut[Continent=="Eurasia"][,.(Bio15_WC,Bio15_CHELSA,Bio15_CRU,Bio15_ERA5,Bio15_TC,Bio15_IMERG,Bio15_CHIRPS)]
sd_bio15[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio15<-sd_bio15[,sd(row_mean)]
data2[from=="bio15"&area=="Asia",coef_brut:=(coef/sd_bio15)]

sd<-brut[Continent=="Eurasia",sd(slope)]
data2[from=="slope"&area=="Asia",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Eurasia",sd(sand)]
data2[from=="sand"&area=="Asia",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Eurasia",sd(org)]
data2[from=="org"&area=="Asia",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Eurasia",sd(ph)]
data2[from=="ph"&area=="Asia",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Eurasia",sd(DBHqm)]
data2[from=="DBHqm"&area=="Asia",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Eurasia",sd(SD)]
data2[from=="SD"&area=="Asia",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Eurasia",sd(BA)]
data2[from=="BA"&area=="Asia",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Eurasia",sd(WDba)]
data2[from=="WDba"&area=="Asia",coef_brut:=(coef/sd)]
```


###Africa
```{r }
mean_ba<-brut[Continent=="Africa"][!is.na(BA),mean(BA)]
sd_ba<-brut[Continent=="Africa"][!is.na(BA),sd(BA)]

mean_dbh<-brut[Continent=="Africa"][!is.na(DBHqm),mean(DBHqm)]
sd_dbh<-brut[Continent=="Africa"][!is.na(DBHqm),sd(DBHqm)]

mean_sd<-brut[Continent=="Africa"][!is.na(SD),mean(SD)]
sd_sd<-brut[Continent=="Africa"][!is.na(SD),sd(SD)]

mean_wd<-brut[Continent=="Africa"][!is.na(WDba),mean(WDba)]
sd_wd<-brut[Continent=="Africa"][!is.na(WDba),sd(WDba)]

mean_agb<-brut[Continent=="Africa"][!is.na(AGB_Feld_Pan),mean(AGB_Feld_Pan)]
sd_agb<-brut[Continent=="Africa"][!is.na(AGB_Feld_Pan),sd(AGB_Feld_Pan)]

mean_agbcont<-brut[Continent=="Africa"][!is.na(AGB_Feld_Cont),mean(AGB_Feld_Cont)]
sd_agbcont<-brut[Continent=="Africa"][!is.na(AGB_Feld_Cont),sd(AGB_Feld_Cont)]

mean_agbreg<-brut[Continent=="Africa"][!is.na(AGB_Feld_Reg),mean(AGB_Feld_Reg)]
sd_agbreg<-brut[Continent=="Africa"][!is.na(AGB_Feld_Reg),sd(AGB_Feld_Reg)]



a<-essais2[area=="africa",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
b<-essais3[area=="africa",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
c<-essais2bis[area=="africa",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
d<-essais[area=="africa",.(from=var,to=sub_rep,coef=estimate)][to=="SD"]#j'ai toutes els directes vers attributs and entre ttributs
g<-essais[area=="africa",.(from=var,to=sub_rep,coef=estimate)][!to=="DBH_qm"&!to=="SD"&!to=="WDba"&!to=="BA"&!to=="AGB_Feld_Cont"&!to=="AGB_Feld_Reg"]# env sur AGB

edges<-rbind(a,b,c,d,g)
edges[to=="DBH_qm",to:="DBHqm"]
edges[!from=="DBH_qm"&!from=="SD"&!from=="WDba"&!from=="BA"]
#standardize the coefficients (in standard deviation and in %)
edges[to=="BA",coef_sd:=coef/sd_ba]
edges[to=="BA",coef_pourc:=(coef/mean_ba)*100]

edges[to=="SD",coef_sd:=coef/sd_sd]
edges[to=="SD",coef_pourc:=(coef/mean_sd)*100]

edges[to=="DBHqm",coef_sd:=coef/sd_dbh]
edges[to=="DBHqm",coef_pourc:=(coef/mean_dbh)*100]


edges[to=="WDba",coef_sd:=coef/sd_wd]
edges[to=="WDba",coef_pourc:=(coef/mean_wd)*100]


edges[to=="AGB_Feld_Pan",coef_sd:=coef/sd_agb]
edges[to=="AGB_Feld_Pan",coef_pourc:=(coef/mean_agb)*100]


edges[to=="AGB_Feld_Reg",coef_sd:=coef/sd_agbreg]
edges[to=="AGB_Feld_Reg",coef_pourc:=(coef/mean_agbreg)*100]


edges[to=="AGB_Feld_Cont",coef_sd:=coef/sd_agbcont]
edges[to=="AGB_Feld_Cont",coef_pourc:=(coef/mean_agbcont)*100]

edges_brut<-edges
edges_brut2<-edges
data<-edges_brut2[,area:="Africa"]
data[,coef_brut:=NA]
data2<-rbind(data2,data)

###non-standardized coefficients

sd_bio1<-brut[Continent=="Africa"][,.(Bio1_WC,Bio1_CHELSA,Bio1_CRU,Bio1_ERA5,Bio1_TC,Bio1_MODIS)]
sd_bio1[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio1<-sd_bio1[,sd(row_mean)]
data2[from=="bio1"&area=="Africa",coef_brut:=(coef/sd_bio1)]

sd_bio12<-brut[Continent=="Africa"][,.(Bio12_WC,Bio12_CHELSA,Bio12_CRU,Bio12_ERA5,Bio12_TC,Bio12_IMERG,Bio12_CHIRPS)]
sd_bio12[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio12<-sd_bio12[,sd(row_mean)]
data2[from=="bio12"&area=="Africa",coef_brut:=(coef/sd_bio12)]

sd_bio15<-brut[Continent=="Africa"][,.(Bio15_WC,Bio15_CHELSA,Bio15_CRU,Bio15_ERA5,Bio15_TC,Bio15_IMERG,Bio15_CHIRPS)]
sd_bio15[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio15<-sd_bio15[,sd(row_mean)]
data2[from=="bio15"&area=="Africa",coef_brut:=(coef/sd_bio15)]

sd<-brut[Continent=="Africa",sd(slope)]
data2[from=="slope"&area=="Africa",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(sand)]
data2[from=="sand"&area=="Africa",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(org)]
data2[from=="org"&area=="Africa",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(ph)]
data2[from=="ph"&area=="Africa",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(DBHqm)]
data2[from=="DBHqm"&area=="Africa",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(SD)]
data2[from=="SD"&area=="Africa",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(BA)]
data2[from=="BA"&area=="Africa",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(WDba)]
data2[from=="WDba"&area=="Africa",coef_brut:=(coef/sd)]
```


###Africa (controlled) 


```{r }

result <- merge(brut, pion[, .(plot, Proportion)], by.x = "PLT_trois_bis", by.y = "plot", all.x = TRUE)
result[is.na(Proportion)&Continent=="Africa",uniqueN(PLT_trois_bis)]#28 plots ont pas

result<-result[Continent=="Africa"][!is.na(Proportion)]
#result<-result[!elevation.y>=1000]

mean_ba<-brut[Continent=="Africa"][!is.na(BA),mean(BA)]
sd_ba<-brut[Continent=="Africa"][!is.na(BA),sd(BA)]

mean_dbh<-brut[Continent=="Africa"][!is.na(DBHqm),mean(DBHqm)]
sd_dbh<-brut[Continent=="Africa"][!is.na(DBHqm),sd(DBHqm)]

mean_sd<-brut[Continent=="Africa"][!is.na(SD),mean(SD)]
sd_sd<-brut[Continent=="Africa"][!is.na(SD),sd(SD)]

mean_wd<-brut[Continent=="Africa"][!is.na(WDba),mean(WDba)]
sd_wd<-brut[Continent=="Africa"][!is.na(WDba),sd(WDba)]

mean_agb<-brut[Continent=="Africa"][!is.na(AGB_Feld_Pan),mean(AGB_Feld_Pan)]
sd_agb<-brut[Continent=="Africa"][!is.na(AGB_Feld_Pan),sd(AGB_Feld_Pan)]

mean_agbcont<-brut[Continent=="Africa"][!is.na(AGB_Feld_Cont),mean(AGB_Feld_Cont)]
sd_agbcont<-brut[Continent=="Africa"][!is.na(AGB_Feld_Cont),sd(AGB_Feld_Cont)]

mean_agbreg<-brut[Continent=="Africa"][!is.na(AGB_Feld_Reg),mean(AGB_Feld_Reg)]
sd_agbreg<-brut[Continent=="Africa"][!is.na(AGB_Feld_Reg),sd(AGB_Feld_Reg)]

mean_prop<-result[Continent=="Africa"][!is.na(Proportion),mean(Proportion)]
sd_prop<-result[Continent=="Africa"][!is.na(Proportion),sd(Proportion)]


a<-essais2_af[area=="africa",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
b<-essais3_af[area=="africa",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
c<-essais2bis_af[area=="africa",.(from=var,to=sub_rep,coef=estimate)]#env sur att D and att sur att D
d<-essais_af[area=="africa",.(from=var,to=sub_rep,coef=estimate)][to=="SD"]#j'ai toutes els directes vers attributs and entre ttributs
g<-essais_af[area=="africa",.(from=var,to=sub_rep,coef=estimate)][!to=="DBH_qm"&!to=="SD"&!to=="WDba"&!to=="BA"&!to=="AGB_Feld_Cont"&!to=="AGB_Feld_Reg"]# env sur AGB

edges<-rbind(a,b,c,d,g)
edges[to=="DBH_qm",to:="DBHqm"]
edges[!from=="DBH_qm"&!from=="SD"&!from=="WDba"&!from=="BA"]
#standardize the coefficients (in standard deviation and in %)
edges[to=="BA",coef_sd:=coef/sd_ba]
edges[to=="BA",coef_pourc:=(coef/mean_ba)*100]

edges[to=="SD",coef_sd:=coef/sd_sd]
edges[to=="SD",coef_pourc:=(coef/mean_sd)*100]

edges[to=="DBHqm",coef_sd:=coef/sd_dbh]
edges[to=="DBHqm",coef_pourc:=(coef/mean_dbh)*100]


edges[to=="WDba",coef_sd:=coef/sd_wd]
edges[to=="WDba",coef_pourc:=(coef/mean_wd)*100]


edges[to=="AGB_Feld_Pan",coef_sd:=coef/sd_agb]
edges[to=="AGB_Feld_Pan",coef_pourc:=(coef/mean_agb)*100]


edges[to=="AGB_Feld_Reg",coef_sd:=coef/sd_agbreg]
edges[to=="AGB_Feld_Reg",coef_pourc:=(coef/mean_agbreg)*100]


edges[to=="AGB_Feld_Cont",coef_sd:=coef/sd_agbcont]
edges[to=="AGB_Feld_Cont",coef_pourc:=(coef/mean_agbcont)*100]

edges[to=="Proportion",coef_sd:=coef/sd_prop]
edges[to=="Proportion",coef_pourc:=(coef/mean_prop)*100]

edges_brut<-edges
edges_brut2<-edges
data<-edges_brut2[,area:="Africa_bis"]
data[,coef_brut:=NA]
data2<-rbind(data2,data)

###non-standardized coefficients

sd_bio1<-brut[Continent=="Africa"][,.(Bio1_WC,Bio1_CHELSA,Bio1_CRU,Bio1_ERA5,Bio1_TC,Bio1_MODIS)]
sd_bio1[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio1<-sd_bio1[,sd(row_mean)]
data2[from=="bio1"&area=="Africa_bis",coef_brut:=(coef/sd_bio1)]

sd_bio12<-brut[Continent=="Africa"][,.(Bio12_WC,Bio12_CHELSA,Bio12_CRU,Bio12_ERA5,Bio12_TC,Bio12_IMERG,Bio12_CHIRPS)]
sd_bio12[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio12<-sd_bio12[,sd(row_mean)]
data2[from=="bio12"&area=="Africa_bis",coef_brut:=(coef/sd_bio12)]

sd_bio15<-brut[Continent=="Africa"][,.(Bio15_WC,Bio15_CHELSA,Bio15_CRU,Bio15_ERA5,Bio15_TC,Bio15_IMERG,Bio15_CHIRPS)]
sd_bio15[, row_mean := rowMeans(.SD, na.rm = TRUE)]
sd_bio15<-sd_bio15[,sd(row_mean)]
data2[from=="bio15"&area=="Africa_bis",coef_brut:=(coef/sd_bio15)]

sd<-brut[Continent=="Africa",sd(slope)]
data2[from=="slope"&area=="Africa_bis",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(sand)]
data2[from=="sand"&area=="Africa_bis",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(org)]
data2[from=="org"&area=="Africa_bis",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(ph)]
data2[from=="ph"&area=="Africa_bis",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(DBHqm)]
data2[from=="DBHqm"&area=="Africa_bis",coef_brut:=(coef/sd)]

sd<-brut[Continent=="Africa",sd(SD)]
data2[from=="SD"&area=="Africa_bis",coef_brut:=(coef/sd)]

sd<-result[Continent=="Africa",sd(Proportion)]
data2[from=="Proportion"&area=="Africa_bis",coef_brut:=(coef/sd)]
```

#The plot with total AGB

##Africa controlled

```{r }
library(ggplot2)
library(dplyr)

# --- Example data to adapt to your own table ---
mydata<-data2[!to=="AGB_Feld_Reg"&!to=="AGB_Feld_Cont"&!from=="Proportion"&!from=="BA"&!from=="DBHqm"&!from=="SD"&!from=="WDba"&!from=="slope"&!from=="sand"&!from=="org"&!from=="ph"&!area=="Africa"]

# --- Create the table with the relationships ---
mydata <- mydata[,.(from, to, area, coef_pourc)]
mydata$from_to <- paste(mydata$from, mydata$to, sep = "_") # do not name this column 'relation'

# --- Reorder by 'from' first (bio1 -> bio12 -> bio15), then 'to'
ordre_from <- c("bio1", "bio12", "bio15")
ordre_to   <- c("WDba", "BA", "DBHqm", "SD", "AGB_Feld_Pan")

mydata <- mydata %>%
  filter(from %in% ordre_from, to %in% ordre_to) %>%
  mutate(
    from = factor(from, levels = ordre_from),
    to   = factor(to, levels = ordre_to),
    from_to = paste(from, to, sep = "_")
  ) %>%
  arrange(from, to)  # sort by 'from' first, then by 'to'

# --- Reorder the Y axis
mydata$from_to <- factor(mydata$from_to, levels = rev(unique(mydata$from_to)))

# --- Order the axes if needed ---
mydata$area <- factor(mydata$area, levels = c("North America","South America", "Africa", "Africa_bis", "Asia", "Oceania"))
mydata$from_to <- factor(mydata$from_to, levels = rev(unique(mydata$from_to)))  # # reverse order for vertical display


# --- Graphe final ---
library(ggplot2)

ggplot(mydata, aes(x = area, y = from_to)) +
  geom_tile(color = "black", fill = "white", linewidth = 0.3, linetype = "dashed")+
  geom_point(
    aes(
      size = abs(coef_pourc),
      color = coef_pourc > 0  # TRUE = vert, FALSE = rouge
    ),
    alpha = 1  # full opacity
  ) +
  scale_color_manual(
    values = c("FALSE" = "firebrick3", "TRUE" = "forestgreen"),
    guide = "none"  # no color legend
  ) +
 scale_size_continuous(
  range = c(1, 18),
  name = "(%)",
  breaks = c(0.1, 1, 5, 10, 15, 20,  30),
  limits = c(0, 31)
)+
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = NULL) +
  theme_minimal() +
  theme(
    axis.text.x.top = element_text(angle = 45, hjust = 0),
    axis.text.y = element_text(size = 10, face = "bold", color = "black"),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_blank()
  )

```


##Africa 

```{r }
library(ggplot2)
library(dplyr)

# --- Example data to adapt to your own table ---
mydata<-data2[!to=="AGB_Feld_Reg"&!to=="AGB_Feld_Cont"&!from=="Proportion"&!from=="BA"&!from=="DBHqm"&!from=="SD"&!from=="WDba"&!from=="slope"&!from=="sand"&!from=="org"&!from=="ph"&!area=="Africa_bis"]

# --- Create the table with the relationships ---
mydata <- mydata[,.(from, to, area, coef_pourc)]
mydata$from_to <- paste(mydata$from, mydata$to, sep = "_") # do not name this column 'relation'

# --- Reorder by 'from' first (bio1 -> bio12 -> bio15), then 'to'
ordre_from <- c("bio1", "bio12", "bio15")
ordre_to   <- c("WDba", "BA", "DBHqm", "SD", "AGB_Feld_Pan")

mydata <- mydata %>%
  filter(from %in% ordre_from, to %in% ordre_to) %>%
  mutate(
    from = factor(from, levels = ordre_from),
    to   = factor(to, levels = ordre_to),
    from_to = paste(from, to, sep = "_")
  ) %>%
  arrange(from, to)  # sort by 'from' first, then by 'to'

# --- Reorder the Y axis
mydata$from_to <- factor(mydata$from_to, levels = rev(unique(mydata$from_to)))

# --- Order the axes if needed ---
mydata$area <- factor(mydata$area, levels = c("North America","South America", "Africa", "Africa_bis", "Asia", "Oceania"))
mydata$from_to <- factor(mydata$from_to, levels = rev(unique(mydata$from_to)))  # # reverse order for vertical display


# --- Graphe final ---
library(ggplot2)

ggplot(mydata, aes(x = area, y = from_to)) +
  geom_tile(color = "black", fill = "white", linewidth = 0.3, linetype = "dashed")+
  geom_point(
    aes(
      size = abs(coef_pourc),
      color = coef_pourc > 0  # TRUE = vert, FALSE = rouge
    ),
    alpha = 1  # full opacity
  ) +
  scale_color_manual(
    values = c("FALSE" = "firebrick3", "TRUE" = "forestgreen"),
    guide = "none"  # no color legend
  ) +
 scale_size_continuous(
  range = c(1, 18),
  name = "(%)",
  breaks = c(0.1, 1, 5, 10, 15, 20,  30),
  limits = c(0, 31)
)+
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = NULL) +
  theme_minimal() +
  theme(
    axis.text.x.top = element_text(angle = 45, hjust = 0),
    axis.text.y = element_text(size = 10, face = "bold", color = "black"),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_blank()
  )

```

```{r }
```